### ISSUE TITLE
Xcode13失效了

### ISSUE THREAD

**Issue by Lyfei** [devdawei/libstdc-#19]
<img width="959" alt="xcode13" src="https://user-images.githubusercontent.com/18715528/136652906-827be1ce-8d02-4b12-b878-59fca77df0b0.png">
用的12的sh

**Comment by Lyfei** [comment]
我傻了，太久没用了。记得改xcode里面的静态库设置。建议作者加入readme里，配套的操作
<img width="945" alt="企业微信20211009-174330@2x" src="https://user-images.githubusercontent.com/18715528/136653223-b21c5e94-9b25-4267-917e-570dd47d831d.png">

**Comment by CrassusX** [comment]
执行命令失败，手工拷贝到相应目录了

**Comment by Dast1Woop** [comment]
执行命令失败,拷贝下面命令执行：
`sudo cp 1/* /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/
sudo cp 2/* /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/
sudo cp 3/* /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/
sudo cp 4/* /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/
`

**Comment by Dast1Woop** [comment]
> 我傻了，太久没用了。记得改xcode里面的静态库设置。建议作者加入readme里，配套的操作 <img alt="企业微信20211009-174330@2x" width="945" src="https://user-images.githubusercontent.com/18715528/136653223-b21c5e94-9b25-4267-917e-570dd47d831d.png">

实测，不改也行，xcode13.1

**Comment by yxg0728** [comment]
Xcode14.1.0执行脚本失败，手动将相应的库拖到对应的文件夹内，编译成功！！！

**Comment by fly8888** [comment]
> 执行命令失败,拷贝下面命令执行： `sudo cp 1/* /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/ sudo cp 2/* /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/ sudo cp 3/* /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/ sudo cp 4/* /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/ `

实测 xcode14.0 通过
